services:
    victoire_core.widget_filter_content_resolver:
        class: Victoire\Widget\FilterBundle\Resolver\WidgetFilterContentResolver
        arguments:
            - '@form.factory'
            - '@router'
            - '@victoire_core.current_view'
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Filter }

    victoire.widget.filter:
        class: Victoire\Widget\FilterBundle\Entity\WidgetFilter

    victoire.widget.form.filter:
        class: Victoire\Widget\FilterBundle\Form\WidgetFilterType
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: form.type }

    victoire.form.filter:
        class: Victoire\Widget\FilterBundle\Filter\FilterType
        tags:
            - { name: form.type }

    victoire.widget.form.filter.subscriber:
        class: Victoire\Widget\FilterBundle\Listener\WidgetFormFilterSubscriber
        arguments:
            - "@=service('victoire_core.filter_chain').getFilters()"
        tags:
            - { name: kernel.event_subscriber }
